[theme]
primaryColor = "#10B981"
backgroundColor = "#F4F7F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1F2937"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[logger]
level = "info"
